title: GratefulDaemon
author: me
subtitle: Nothing worth reading.

url: "https://bippyboppy.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr/parchment"
footer_text: "Theme by rhl-bthr"

profile-picture: assets/profile.png
favicon_location: assets/fav.png

permalink: /:year-:month-:day-:title/
sass:
  style: compressed
  sass_dir: css

navbar:
  - name: "About"
    link: "about"
  - name: "tags"
    absolute-link: "https://bippyboppy.github.io/tags/"
